<?php

return [
	'MAKE_REPORT' => [
		'MAKE_SALE' => 100
	   ,'MAKE_QUOTATION' => 101
	   //,'MAKE_SERVICEQUOTATION' => 102
	   //,'MAKE_MATERIALLIST' => 103
	   //,'MAKE_OPERATIONREPORT' => 104
	],
	'SHOW_REPORTS' => [
		'SHOW_SALES' => 105
	   ,'SHOW_QUOTATIONS' => 106
	   //,'SHOW_SERVICEQUOTATIONS' => 107
	   //,'SHOW_MATERIALLISTS' => 108
	   //,'SHOW_OPERATIONREPORTS' => 109
	],
	'DELETE_REPORT' => [
		'DELETE_SALE' => 138
	   ,'DELETE_QUOTATION' => 139
	   //,'DELETE_SERVICEQUOTATION' => 140
	   //,'DELETE_MATERIALLIST' => 141
	   //,'DELETE_OPERATIONREPORT' => 142
	],
	'SHOW_INVENTORY' => [
		'SHOW_PRODUCTS' => 110
	   ,'SHOW_STOCKS' => 111
	   ,'SHOW_SUPPLIERS' => 112
	   //,'SHOW_MATERIALS' => 113
	   //,'SHOW_SERVICES' => 114
	   //,'SHOW_OPERATIONS' => 115
	],
	'ADD_INVENTORY' => [
		'ADD_PRODUCTS' => 116
	   ,'ADD_STOCKS' => 117
	   ,'ADD_SUPPLIERS' => 118
	   //,'ADD_MATERIALS' => 119
	   //,'ADD_SERVICES' => 120
	   //,'ADD_OPERATIONS' => 121
	],
	'UPDATE_INVENTORY' => [
		'UPDATE_PRODUCTS' => 122
	   ,'USE_STOCKS_MANUALLY' => 143
	   ,'UPDATE_SUPPLIERS' => 123
	   //,'UPDATE_MATERIALS' => 124
	   //,'UPDATE_SERVICES' => 125
	   //,'UPDATE_OPERATIONS' => 126
	],
	'DELETE_INVENTORY' => [
		'DELETE_PRODUCTS' => 127
	   ,'DELETE_SUPPLIERS' => 128
	   //,'DELETE_MATERIALS' => 129
	   //,'DELETE_SERVICES' => 130
	   //,'DELETE_OPERATIONS' => 131
	],
	'MANAGE_USERS' => [
		'SHOW_USERS' => 132
	   ,'SHOW_USER_PRIVILEGES' => 133
	   ,'SHOW_USER_ACTIVITIES' => 146
	   ,'UPDATE_USER_PRIVILEGES' => 134
	   ,'DOWNLOAD_USER_ACTIVITIES' => 147
	   ,'ADD_USERS' => 135
	   //,'DELETE_SERVICES' => 136
	   ,'DELETE_USERS' => 137
	],
	'OTHERS' => [
		'VIEW_PDFS' => 144
	   ,'SEND_EMAILS' => 145
	]

	//### LAST ID : 147
];
